spring:
  application:
    name: spring-barebones-01
#  config:
#    import: optional:classpath:.env[.properties]
#  datasource:
#    url: jdbc:postgresql://aws-0-eu-central-1.pooler.supabase.com:6543/postgres?user=postgres.nytforpyzmtichiygwbe&password=${DB_PW}
#    driver-class-name: org.postgresql.Driver
#  jpa:
#    show-sql: true
#    defer-datasource-initialization: true
#    hibernate:
#      ddl-auto: none